name: appbar_example
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^5.7.10
  flutter_icons: ^1.1.0

  cupertino_icons: ^1.0.0
  app: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/background.jpg
    - assets/images/logomegacity.png
    - assets/images/cidadeanimada.jpg
    - assets/images/homepage.png


Fonts:
  - family: Roboto
    fonts:
     - assets: assets/fonts/Roboto.ttf
   